### ISSUE TITLE
Raum archivieren Navigationstack

### ISSUE THREAD

**Issue by c-roth** [die-gruppe-c/Quotierte-Redeliste#27]
Nachdem ein Raum archiviert wurde ist der erste Startbildschirm noch im Navigationstack d.h. man kann wieder zurück navigieren.
![Screen Shot 2019-06-12 at 17 23 35](https://user-images.githubusercontent.com/40185226/59364350-0221d480-8d37-11e9-9ff8-e4c3ea08599a.png)

**Comment by schalterDev** [comment]
Tritt bei mir nicht auf. Weder beim Moderator noch beim Client
